### ISSUE TITLE
Wrong breaks with textnodes containing soft hyphens

### ISSUE THREAD

**Issue by aleray** [FremyCompany/css-regions-polyfill#23]
Hi,

first of all thanks for the polyfill: it is truly impressive!

I'm using it on Chromium, with content that contains soft hyphens. If the region break occurs on a word that has one, the first part of the word may overflows, hanging on an extra line whereas it should go to the next region.

Below is an image that illustrates it:

![css-region-soft-hyphens-overflow](https://cloud.githubusercontent.com/assets/67232/10119773/a21b0862-64a0-11e5-9730-09d410b729db.png)

I'm wondering if it has to do with this regex, line 3724 in the current build:

```javascript
            // move to the next non a-zA-Z symbol
            var currentText = r.startContainer.nodeValue;
            var currentOffset = r.startOffset;
            var currentLetter = currentText[currentOffset++];
            while(currentOffset < max && /^\w$/.test(currentLetter)) {
                currentLetter = currentText[currentOffset++];
            }
            r.setStart(r.startContainer, currentOffset);
```

Could you have a look? If not, could you give any clues that would help looking in the right direction?

Thanks a lot,

Alex

[edit]: does not seem to occur on Firefox.

**Comment by FremyCompany** [comment]
I don't think the regular expression is the cause of the problem. I tested and a soft hypen doesn't match it, so it will be considered as a possible stopping point. Now, the question is why is the whole word eaten and not the word until the soft hypen. That's a good question, but I've no time to dig this issue in the coming days as I'm in the process of relocating to Redmond, USA (from Brussels, Belgium) and will start my new job on next Monday. 

I promise that as soon as I get some free time, I'll have a closer look at the problem, however.

**Comment by aleray** [comment]
Thanks a lot François. I've been looking more deeply into it and although it was nice to discover the mechanic of your polyfill I didn't manage to spot were the break was happening. Hope you have time to look into it!

**Comment by aleray** [comment]
Hi François,

a friend who is a more talented programer than I am had a quick look at your code. I sent him those two minimal exemples to demonstrate the bug:

without conditional hyphens:
http://codepen.io/anon/pen/GpyNMr

With conditional hypens, the bug happens:
http://codepen.io/anon/pen/zvpozb

In the conditional hyphens exemple, flows sometime overflow whereas it doesn't happen without conditional hyphens. The problems show up in Chrome. In Firefox it is slightly better but come with its erros too (weird alignment at the top, and conttainers bottom margins).

He had a look and found a dirty fix by changing from:

```javascript
if(this.collapsed && rect.top===0 && rect.bottom===0) {
```
to:

```javascript
if(rect.top===0 && rect.bottom===0) {
```

Unfortunatly applied to more complex exemple it breaks again but I hope it can give you some clues about the source of the error.

Good day,

Alex

**Comment by FremyCompany** [comment]
Thanks for investigating this further. I'll try to work on this during the week-end

**Comment by aleray** [comment]
We have a deadline on monday morning so that'd be perfect! ;)

**Comment by aleray** [comment]
we are thinking of you very much now :)

**Comment by FremyCompany** [comment]
I'm sorry. I had a very bumpy Saturday and I went to visit apartments this Sunday. Didn't have much time for myself. I'll get to it asap, but I can't make any promise right now...

**Comment by aleray** [comment]
No worries. We found that manually removing the offending conditional hypens fixed the problem. It is not ideal (in case a text has to change last minute) but it will do. Again, thanks a lot for your library!

**Comment by FremyCompany** [comment]
Enjoy ;-)

> Chrome did not report the position of soft hyphens, considering them as whitespace, causing bugs. There was a mitigation in place to avoid this bug for whitespace in general, for for some reason a refactoring must have broken it (and I never found out as another, more general mitigation did hide this in the case of true whitespace). 

This is now fixed. As a bonus, soft hyphens now display when a word is broken across regions.

**Comment by aleray** [comment]
Hi there,

I was away and I just tested the last version. Thanks a lot for your work, it works like a charm!!!

Banana smile :)

**Comment by FremyCompany** [comment]
:+1:

**Comment by andremacola** [comment]
@FremyCompany are you sure? For me hyphens across regions is not working.
