### ISSUE TITLE
Containers not updated when showing the content

### ISSUE THREAD

**Issue by tlechauve** [FremyCompany/css-regions-polyfill#24]
Hi,

First the example: http://codepen.io/anon/pen/EVNqZW?editors=110

Then the explanation:
I would like to apply this polyfill on a large set of regions that is hidden (except the first) then manually showed, but it appears that when i set display to other that none, the content is not fit into the container. Is there a way to ensure that even if my container is not display, he's still well filled ?

Thanks =)

**Comment by FremyCompany** [comment]
CSS Regions cannot fill regions which are hidden, and I'm even having trouble filling regions as their layout is changed, whether or not this involves showing/hiding the region or not. Try to have your region positioned absolutely outside of the page, or use visibility: none?

**Comment by tlechauve** [comment]
That worked like charm, thanks =)

**Comment by FremyCompany** [comment]
Glad it worked for you :-)
