### ISSUE TITLE
polyfill in webkit (conflicts with native implementation if you force it to run)

### ISSUE THREAD

**Issue by latsami** [FremyCompany/css-regions-polyfill#26]
Hi F.,
the polyfill works super fine in Chromium and Firefox, actually even better than the native regions in Webkit which fails with Flexbox or float: left elements (see screenshot below).

![2015-10-07_13-53-01_screenshot](https://cloud.githubusercontent.com/assets/173763/10336688/e20999a4-6cfa-11e5-9e35-f265c4a285ec.png)

I saw in your code that you managed the case of Webkit, but when applied, the <cssregion> tags are empty. Is there a way to figure out what's going on?

Here's an example page which works fine on Firefox + Chromium, but is empty in Webkit: 
http://diplomes2015.villa-arson.org/aude-van-wyller/?template=page_print

I hope you have time to have a look at it.
Thanks!
S.

**Comment by FremyCompany** [comment]
Hi. I'm currently in the process of relocating to Seattle and don't have a computer where I could actually try the issue. I suspect that the polyfills try to run in webkit even though webkit already supports the property. 

I'll try to figure out what's going on this week-end but I can't make any promise ;-)

**Comment by latsami** [comment]
Hi F.
Indeed, it is applying the polyfill anyways, but actually I would like to apply it also on webkit, as without the polyfill, the native CSS regions don't flow correctly (seen in the screenshot). I actually have better results *with* the polyfill. But then I don't get why the polyfill in webkit just makes everything disappear.
Anyways, take you time to settle in this exciting new life!
Best from Bxl.

**Comment by FremyCompany** [comment]
The polyfill doesn't make things disappear, the native implementation does. The polyfill spreads the content in the regions but the content of the regions is ignored by webkit which tries to split the content in the regions, too. However, after the polyfill has done its job, there's no content left to distribute so all regions end up being empty.

A fix would be to prefix all polyfill properties in the code, so that the polyfills listen to "-fc-flow-into" and not "flow-into" as the latter seems to be recognized by webkit. I'm not sure how hard such a refactoring would be in the code, though the only two properties to rename are "flow-from" and "flow-into".

**Comment by latsami** [comment]
Well, I feel a bit ashamed to not have thought of removing the -webkit-flow-into/from. It works by just leaving flow-into/from.

Btw, is there a way to run a function once the polyfill has finished its work? 
I inflated the number of pages needed because of the "break-after: always". And then I would like to remove the pages which have empty <cssregion> tags. For the moment, I use a setTimeout, but it's not very optimal. ;)

Thanks a lot for your help!

**Comment by FremyCompany** [comment]
Sure, you can listen to the events and I think they should fire once the work is done.

```
document.getNamedFlow('name-of-flow').addEventListener('regionfragmentchange', ...);
```

I'm marking this issue as resolved as Safari did not unprefix its implementation so there's no conflict yet. By the time they unprefix it, it will be pretty solid so you won't need the polyfill so the conflict doesn't look like an issue I should work on at this time.
