### ISSUE TITLE
Callback when polyfill has done its work

### ISSUE THREAD

**Issue by latsami** [FremyCompany/css-regions-polyfill#27]
Hello R.,
hope you're setting up well in the U.S.
In my last issue, you suggested a way to call a function when the polyfill was done.
I tried this but it doesn't output anything in the console:

     document.getNamedFlow('myStory').addEventListener('regionfragmentchange', function(event) {
        console.log('regionFragmentChange');
    });

I'm not very familiar with managing complex events I must say.
Can you guide me on this?
Thanks!

**Comment by FremyCompany** [comment]
You can have a look at https://github.com/FremyCompany/css-regions-polyfill/blob/master/test/css-regions/region-test-9.html

This examples does exactly what you want to do, I guess.

If you don't see any event firing, I guess it means you register to the stream only after the reflow has already been done (or there's some bug in my code which prevents the event firing in this case). If this is the latter, I would need a test case to start with.
