### ISSUE TITLE
Don't work with Drupal

### ISSUE THREAD

**Issue by Copylefter** [FremyCompany/css-regions-polyfill#29]
I don't know why it is happend, but regions don't work inside drupal website, while they works in static layout. I break down my brain trying to undestand why it is happend. May be you will have some ideas?

Static where they work -  html http://decoracia.copylefter.org/haecker.html 
Drupal theme where they don't - http://decor.akute.ru/brands/creazioni

Regions are under the future image

**Comment by Copylefter** [comment]
Also wanna add that on safari drupal version is working

**Comment by FremyCompany** [comment]
Closing because this issue is kinda old and I never got a chance to really look at it. The issue might or might not have fixed by now, but this is difficult to tell.
