### ISSUE TITLE
When disabling then enabling region flowing again, DOM order seems reversed

### ISSUE THREAD

**Issue by raphaelgoetter** [FremyCompany/css-regions-polyfill#34]
Hello,

I'm testing the polyfill on this codepen : 
http://codepen.io/raphaelgoetter/pen/aNrrNO

It works great when you resize the window for the first time... but the next times, the DOM order is reversed ("login" appears at the end for example).

Do you understand what I mean and could you fix that bug ?

Raphaël

**Comment by FremyCompany** [comment]
Thanks for reporting the issue. It took me some time to figure the exact repro steps (resizing the window isn't enough, you have to resize past the media query breaking point), but I can repro the issue now. 

Really weird, isn't it... I'll try to have a look this weekend because that doesn't look like a crazy edge case, it really should work by default.

**Comment by FremyCompany** [comment]
Ok, I found the issue. During the first layout, nodes are inserted naturally in dom order. This is not the case on later cases. There was a very clever code to put them back in dom order while minimizing marshalling cost between DOM and Javascript, but it didn't work as expected when the nodes being inserted where not sibling of each other, like in your case. 

> - FILTER_REJECT
>   - Reject the node. Navigation methods defined for NodeIterator or TreeWalker will not return this node.
>   - **For TreeWalker, the children of this node will also be rejected**. 
>   - NodeIterators treat this as a synonym for FILTER_SKIP.
> - FILTER_SKIP
>   - Skip this single node. Navigation methods defined for NodeIterator or TreeWalker will not return this node.
>   - For both NodeIterator and TreeWalker, the children of this node will still be considered.

Code was there:
```
	cssRegions.Flow.prototype.addToContent = function(element) {
		
		// walk the tree to find an element inside the content chain
		var content = this.content;
		var treeWalker = document.createTreeWalker(
			document.documentElement,
			NodeFilter.SHOW_ELEMENT,
			function(node) { 
				return content.indexOf(node) >= 0 ? NodeFilter.FILTER_ACCEPT : NodeFilter.FILTER_REJECT; 
			},
			false
		); 
		
		// which by the way has to be after the considered element
		treeWalker.currentNode = element;
		
		// if we find such node
		if(treeWalker.nextNode()) {
			
			// insert the element at his current location
			content.splice(content.indexOf(treeWalker.currentNode),0,element);
			
		} else {
			
			// add the new element to the end of the array
			content.push(element);
			
		}

	};
```

I am going to change this code to either use TreeWalker properly by using NodeFilter.FILTER_SKIP, or do a binary seach inside content. Still not sure.

**Comment by raphaelgoetter** [comment]
Great job, thank you !

**Comment by FremyCompany** [comment]
Reopening issue as the same code was also used for addToRegions so the issue might persist in some cases. Will fix tonight.
