### ISSUE TITLE
Soft hyphens not hyphenating at region break

### ISSUE THREAD

**Issue by timed0** [FremyCompany/css-regions-polyfill#39]
At least on recent chrome soft hyphens are not shown when a word is hyphenated across region breaks. It appears that the &shy; gets cut into the next region rather than left trailing on the current. I modified the test as below and it fixes it for me:

```
				var nodeValue = tmp.nodeValue.replace(/(\s|\r|\n)*$/,'');
        			if(nodeValue) {
				    // if the last cut was just before or after 
                                    // a &shy; (soft hyphen), we need to append a dash 
                                    if(/\u00AD$/.test(nodeValue)) {
				      nodeValue = nodeValue.replace(/\u00AD$/, '-');
				    } else if(overflowingContent.textContent[0] == '\u00AD') {
                                      nodeValue = nodeValue + '-';
                                    }
				    tmp.nodeValue = nodeValue;
				} else {
					tmp.parentNode.removeChild(tmp);
				}
```
Sorry I haven't generated a pull request,.

**Comment by FremyCompany** [comment]
Thanks! 

I'm not entirely sure how it is possible Chrome gets in this situation, but it also doesn't strike me as impossible so I just merged your proposal, as it doesn't seem to be it could end up causing problem. If the situation you test for happens, the behavior you added seems to be what you would want.

**Comment by andremacola** [comment]
Still not working for me
