### ISSUE TITLE
word counting is not good in FF74, 

### ISSUE THREAD

**Issue by mrbbp** [FremyCompany/css-regions-polyfill#43]
When testing simple text flowing exemple with font-size over 2rem, a decay appear on firefox and word are cropped (there is a overflow: hidden as you recommand).
Perhaps it is a word's width ou letter's width estimation who is not the same in Chrome and FF.

![css_region_chromevsFF](https://user-images.githubusercontent.com/1716290/79213533-a5f17a80-7e49-11ea-8b01-d5fdc33dee36.jpg)
[css_regions_js.html.zip](https://github.com/FremyCompany/css-regions-polyfill/files/4474651/css_regions_js.html.zip)

**Comment by FremyCompany** [comment]
Hi,

The polyfill does normally not affect the horizontal positioning of words, so if words overflow in the horizontal direction, I would look for something in the general css rather than the region code itself.

I will take a quick look to see if I can spot something out of the hand.

**Comment by FremyCompany** [comment]
Ok, I found what the problem was.

Firefox added "block-size" as an alias for "width", and that property now gets copied as part of the style of the element while that shouldn't be the case. 

> Where the error happens (style getting copied)
> https://github.com/FremyCompany/css-regions-polyfill/blob/master/src/css-regions/lib/helpers.js#L451
> Where the error comes from
> https://github.com/FremyCompany/css-regions-polyfill/blob/master/src/core/css-cascade.js#L202

Would you be able to test a fix and make a pull request? I don't have this repository cloned anywhere right now.

**Comment by uptownnickbrown** [comment]
I believe this is addressed by https://github.com/FremyCompany/css-regions-polyfill/pull/45 . Thanks for the pointer to `css-cascade.js` 👍 .
