### ISSUE TITLE
display:none on the .content as requested does not work

### ISSUE THREAD

**Issue by mrbbp** [FremyCompany/css-regions-polyfill#44]
You recommend to add a `display:none` to the content block, but i was enable to activate simple example of flowing text until i remove this css rule.
Please adjust you recommendations in the main page.

regards.

**Comment by FremyCompany** [comment]
This is probably true. Browsers at some point agreed to update their code to stop reporting styles properly for elements in a display:none subtree. I'll remove the recommendation.

**Comment by FremyCompany** [comment]
Fixed
