### ISSUE TITLE
Unknown css selectors throw an exception

### ISSUE THREAD

**Issue by RonaldTreur** [FremyCompany/css-regions-polyfill#46]
At first glance, this makes sense, but unfortunately Chrome (for example) is not familiar with (some?) of the Mozilla prefixed selectors and hence those break this polyfill.

For instance, having this selector (taken from [an example on MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/::-moz-focus-inner), but also part of the HTML5 Boilerplate's [normalize.css](https://github.com/h5bp/html5-boilerplate/blob/master/dist/css/normalize.css)):
`button::-moz-focus-inner`

will make this code throw:
https://github.com/FremyCompany/css-regions-polyfill/blob/f508484fbe5d4f208c3592a4e71e729e06582169/src/core/css-cascade.js#L132-L140

Specifically, line 133 will right away break.

I wonder if this is necessary. I am pretty sure if the selector would simply be ignored, everything would continue to run smoothly. Unknown selectors can be safely skipped after all.

**Comment by FremyCompany** [comment]
It throws, but this is not blocking the code. The error is caught and rethrown in the setImmediate. I do that so there is a warning in the code when a selector is incorrect. It is probably ok to remove the catch() handling but it is not an issue except that it logs messages that are unwanted in the console.

**Comment by RonaldTreur** [comment]
Hi @FremyCompany, you are completely right of course! This does (fortunately) not block any code. When I see an uncaught exception pop up in my console however, I'll investigate it. So it took me a few moments to realise this is not an actual problem and I dare to assume I am not the only dev who took the time to do that. Since it is absolutely not relevant for any part of the algorithm, I wholeheartedly agree that the catch()-handling can go. I can create a PR for that if you agree.

**Comment by FremyCompany** [comment]
I went ahread and fixed this in https://github.com/FremyCompany/css-regions-polyfill/commit/d40c91b388b490cf29fb92ab307f67e5c5015c6c

**Comment by RonaldTreur** [comment]
Awesome, thanks!
