### ISSUE TITLE
Scaled regions mess up the algorithm

### ISSUE THREAD

**Issue by RonaldTreur** [FremyCompany/css-regions-polyfill#49]
When a scaling transformation is applied to a region (or one of its ancestors), this messes up the polyfill's algorithm in deciding where to cut off that region's content exactly. In effect it will cut it off too late when the region is scaled down, and too early when it is scaled up.

This can be easily verified by applying the following CSS to a region (or one of its ancestors):
`transform: scale(2);`. Its content will be cut roughly in half.

### Why this happens

The reason for this is that the algorithm compares the "intrinsic" height of the region (its `offsetHeight`) with the space a Range takes up relative to the viewport (via its `getBoundingClientRect`-method). When the scale is 1, this works just fine. But once a different scale is applied, the intrinsic height of the region remains unchanged, whereas the space the Range takes up in the viewport will change.

The code that retrieves the `offsetHeight` and `offsetWidth` can be found here on lines 250 & 251:

https://github.com/FremyCompany/css-regions-polyfill/blob/f508484fbe5d4f208c3592a4e71e729e06582169/src/css-regions/polyfill.js#L249-L253

### Possible fix

My suggestion to fix this, is to also switch to the `getBoundingClientRect`-method when determining the width & height of the region. This would make sure we are comparing apples with apples.

Both an element's offsetHeight and its boundingClientRect take the element's padding and border into account, so no other change seems necessary.

There is however one tiny difference between both: the offsetHeight is always rounded to an integer, whereas the boundingClientRect returns a float. I think this is inconsequential, though if I am wrong the outcome could simply be rounded to an integer afterwards.

### IE 8?

Interestingly, the element's boundingClientRect is already requested -as can be seen on line 252- but only to get the coordinates of the element's edges. I expect this is because in IE8 this method does not return a `width` and `height`, and so it could not be used to retrieve the actual dimensions. But we could be simply calculate them using the edge-information that is supplied.

**Comment by FremyCompany** [comment]
This sounds like a good fix, thanks. IE8 support isn't nearly as important as it used to be :)
Hopefully the math you wrote does check out, but even if it doesn't, this shouldn't matter much.
